-- MySQL Script generated by MySQL Workbench
-- Wed May  6 17:13:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sempdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sempdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sempdatabase` DEFAULT CHARACTER SET utf8 ;
USE `sempdatabase`;

-- -----------------------------------------------------
-- Table `sempdatabase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sempdatabase`.`users` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `userType` VARCHAR(45) NOT NULL DEFAULT 'Assistant',
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB;

-- Insert superuser as an default admin user default password is root. Change this first!
INSERT IGNORE INTO `sempdatabase`.`users`
  SET `userName` = 'Admin',
  `password` = '4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2',
  `userType` = 'Admin';


-- -----------------------------------------------------
-- Table `sempdatabase`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sempdatabase`.`locations` (
  `locationID` INT NOT NULL AUTO_INCREMENT,
  `locationName` VARCHAR(45) NOT NULL,
  `xCoordinate` VARCHAR(45) NOT NULL,
  `yCoordinate` VARCHAR(45) NOT NULL,
  `minTime` INT NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`locationID`),
  UNIQUE INDEX `locationID_UNIQUE` (`locationID` ASC),
  UNIQUE INDEX `locationName_UNIQUE` (`locationName` ASC))
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
